<?php

/**
 * @file
 * Hook implementations for the amazee.ai AI provider.
 */

use Drupal\ai_search\Plugin\search_api\backend\SearchApiAiSearchBackend;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserInterface;
use Drupal\Core\TempStore\TempStoreException;
use Drupal\search_api\IndexInterface;
use Drupal\Core\Url;

/**
 * Implements hook_search_api_index_update().
 *
 * When the search API index is updated, check the fields are correctly
 * setup in Postgres.
 */
function ai_provider_amazeeio_search_api_index_update(IndexInterface $index): void {
  $server = $index->getServerInstance();
  if (!($server->getBackend() instanceof SearchApiAiSearchBackend)) {
    return;
  }
  $backend_config = $server->getBackendConfig();
  if (!isset($backend_config['database'])) {
    return;
  }
  if ($backend_config['database'] !== 'postgres-amazeeai') {
    return;
  }
  $ai_vdb_provider_postgres = \Drupal::service('ai.vdb_provider')->createInstance('postgres-amazeeai');
  $connection = $ai_vdb_provider_postgres->getConnection($backend_config['database_settings']['database_name']);
  \Drupal::service('ai_provider_amazeeio.postgres_client')->updateFields(
    $index->getFields(),
    $backend_config['database_settings']['collection'],
    $connection,
  );
}

/**
 * Implements hook_user_logout().
 */
function ai_provider_amazeeio_user_logout(AccountInterface $account): void {
  // Log the user out of amazee.ai during Drupal logout.
  _ai_provider_amazeeio_amazee_logout();
}

/**
 * Implements hook_user_login().
 */
function ai_provider_amazeeio_user_login(UserInterface $account): void {
  // Log the user out of amazee.ai during log in in case the last Drupal logout was
  // due to timeout/inactivity.
  _ai_provider_amazeeio_amazee_logout();

  // Trigger (flag) the redirect to the settings page, if needed.
  _ai_provider_amazeeio_redirect_to_settings_page();
}

/**
 * Helper function to redirect the user to the amazee.ai AI settings page after
 * login, if there is no API key.
 *
 * It is important to know that this function does not trigger the redirect
 * itself, it just flags that a redirect to a specific page should be done.
 * This method just adds the destination parameter, so it doesn't halt the
 * execution of the process. It means that this will work for example on form
 * submissions, or other types of operations that will trigger the redirect
 * after they completed the execution..
 *
 * @return void
 */
function _ai_provider_amazeeio_redirect_to_settings_page(): void {
  $configFactory = \Drupal::configFactory();
  // Only run this if config ai_provider_amazeeio.settings.redirect_on_login is
  // TRUE.
  $config = $configFactory->get('ai_provider_amazeeio.settings');
  if (!$config->get('redirect_on_login')) {
    return;
  }

  $currentUser = \Drupal::currentUser();
  if ($currentUser->hasPermission('administer ai providers')) {
    // Call ai_provider_amazeeio.api_client->getPrivateApiKeys() and log the result.
    $apiClient = \Drupal::service('ai_provider_amazeeio.api_client');
    $apiKey = $apiClient->getPrivateApiKey($config->get('api_key'));
    if (is_null($apiKey)) {
      // Triggering a redirect without halting the execution is something that
      // was also discussed here: https://www.drupal.org/project/redirect_after_login/issues/3214949
      // There are basically two options proposed in that issue:
      // 1. Using a middleware, see comment nr #25 for an implementation.
      // 2. Using a destination parameter on the current request, see nr. #107
      // for an implementation.
      // The advantage of the second option is that is lighter, and it does not
      // add a new call on every request (the option 1 would basically just add
      // another middleware into the queue which will be executed on every
      // request). For that reason, the following implementation uses the second
      // approach.
      $url = Url::fromRoute('ai_provider_amazeeio.settings_form')->toString();
      \Drupal::service('request_stack')
        ->getCurrentRequest()->query->set('destination', $url);
    }
  }
}

/**
 * Helper function to log user out of amazee.ai system.
 */
function _ai_provider_amazeeio_amazee_logout(): void {
  /** @var \Drupal\ai_provider_amazeeio\AmazeeIoApi\ClientInterface $amazee_client */
  $amazee_client = \Drupal::service('ai_provider_amazeeio.api_client');
  $amazee_client->logout();

  /** @var \Drupal\Core\TempStore\PrivateTempStoreFactory $temp_store */
  $temp_store = \Drupal::service('tempstore.private');
  try {
    $temp_store->get('amazeeio_ai')->delete('access_token');
  }
  catch (TempStoreException $e) {
    // Log error but do nothing as this shouldn't affect the user.
    \Drupal::logger('ai_provider_amazeeio')->error('Failed to log out of amazee.ai: @error', ['@error' => $e->getMessage()]);
  }
}
